## Devops for Data Scientists Pre-questionairre

By filling out this survey, you will provide us with helpful information to ensure that the training is helpful to you.

1.  What is your current work position?
2.  Have you ever administered or installed any of the following Posit Products?
    -   Posit Team

    -   Posit Workbench

    -   Posit Connect

    -   Posit Package Manager

    -   Posit Docker Products

    -   Rstudio Server (Open Source)

    -   Rstudio Server Pro

    -   Shiny Server (Open Source)

    -   Shiny Server Pro
3.  What is your computer's OS?
    -   Linux
    -   Windows
    -   Mac (Intel-processor)
    -   Mac (M1/M2 Silicon processor)
    -   Don't Know
4.  Are you able to download applications onto your computer? Yes, No, Don't Know
5.  Do you have an active (and usable) account for any of the following? Yes, No, Don't Know
    -   Github
    -   AWS
    -   GCP
    -   Microsoft Azure
    -   Docker Hub
6.  How strong are your skills in the following: (1-I do not use it...5-I am the one folks come to for help)
    -   R
    -   Python
    -   Linux
    -   Bash/shell scripting
    -   Docker
7.  How comfortable are you currently with? (from 1 -never done this before to 5 -very comfortable
    -   accessing files via the command line
    -   using git in the command line
    -   collaborating with coworkers on code with git (using a GUI or the terminal)
    -   Using CI/CD to deploy content (ex. Github Actions, Jenkins, etc)
    -   Using Linux commands to access and edit files
    -   Using SSH to remote into a Linux virtual machine

What do you hope to learn from this course?
